### ISSUE TITLE
Breaking change introduced in 1.3.2

### ISSUE THREAD

**Issue by jonatan-ivanov** [prometheus/client_java#1189]
It seems `1.3.2` was released with some breaking changes (compared to `1.3.1`). This is unexpected given that it is a patch release.

The change was introduced here: https://github.com/prometheus/client_java/commit/eb48f5d1ea6de3e8833f8c3898191ef6bc7844a3#diff-03bebb9eaf09f2cec3a24afb7ff939663924dd8b47ed8612bf5fcef9edd2e018R36

The commit is big, please wait a few seconds so that your browser can load it and jump there, if it does not work, scroll to `MetricSnapshots.java#36`:
```diff
- public MetricSnapshots(Collection<MetricSnapshot> snapshots) {
+ public MetricSnapshots(Collection<MetricSnapshot<?>> snapshots) {
```

Which can cause compiler errors, it is a breaking change in a public class. In Micrometer, the compiler error we get is:
```
MicrometerCollector.java:88: error: no suitable constructor found for MetricSnapshots(Collection<MetricSnapshot>)
        return new MetricSnapshots(metricSnapshots);
```

I think this change was causing compile-time failures in the Prometheus Client during refactor but here is a simple reproducer that is ok with `1.3.1` but fails with 1.3.2:
```java
Collection<MetricSnapshot> collection = new ArrayList<>();
MetricSnapshots metricSnapshots = new MetricSnapshots(collection);
```

**Comment by fstab** [comment]
Thanks Jonatan! This wasn't intentional, I think we should revert it and make another patch release.

**Comment by zeitlinger** [comment]
Yes, I wasn't aware that this is part of the public API (because we have no internal packages).

Otel has already adjusted to this change in https://github.com/open-telemetry/opentelemetry-java/pull/6805 - so we have to decide if want to roll back or just declare it a breaking change.

**Comment by shakuzen** [comment]
The maintainers here are free to choose what they want to do, and I don't know if there's an explicit versioning/compatibility policy for this project, but I think it would create less potential future issues to revert the breaking change and release a new patch version. As far as I can tell, otel-java has not released a version since merging that change, so it isn't something available to users in a released version yet anyway. Micrometer has a scheduled release on Monday. We can adapt to the change but then that makes our code incompatible with versions of the Prometheus client before this breaking change, which may or not be a problem for users depending on how they manage versions, but it would be generally unexpected for any patch version in a minor to not be a drop-in replacement in terms of API/ABI compatibility.

As a side note, introducing something like [japicmp](https://siom79.github.io/japicmp/) could help catch breaking changes as part of the build.

**Comment by zeitlinger** [comment]
That's a reasonable ask - I'll create a release this week, which you can include in the next micrometer release.

**Comment by zeitlinger** [comment]
Fixed in #1189

**Comment by jonatan-ivanov** [comment]
Thank you, do you have an ETA to release it (`1.3.3`)?

**Comment by zeitlinger** [comment]
> Thank you, do you have an ETA to release it (`1.3.3`)?

Nov 8

**Comment by jonatan-ivanov** [comment]
Thank you!
