### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by mirthy** [prometheus/client_java#122]
Hi, thanks for all the great work on this.  It's been a little while since we've had a release, any chance we could cut a new release that includes some of the new clients?  Please? :smile:

**Comment by dennisosimon** [comment]
+1

**Comment by HenrikSkriver** [comment]
Hi
Thanks to @tokuhirom and @brian-brazil for getting the spring-boot client ready.

I have integrated the spring-boot client into a service by building a 0.0.15-SNAPSHOT locally and would also like to get a release with this new spring-boot client or even just get the public 0.0.15-SNAPSHOT updated so that it contains the spring-boot client.

Thank you in advance.

**Comment by brian-brazil** [comment]
This is done.
