### ISSUE TITLE
Performance issue when scape

### ISSUE THREAD

**Issue by dliu-aspira** [prometheus/client_java#1232]
Shall we change below code to avoid the performance issue?

![image](https://github.com/user-attachments/assets/5946fde8-2a56-49d5-ad5e-355a403a27ce)
![image](https://github.com/user-attachments/assets/5c497753-5be8-4ee6-9f04-0832357118ca)

**Comment by fstab** [comment]
Good point, if this has a performance issue we should change it.

However, rather than changing the behavior of `containsMetricName()` I'd rather add a new method `containsPrometheusMetricName()` and keep `containsMetricName()` backwards compatible.

So eventually `containsMetricName()` could be implemented like this

```
    public boolean containsMetricName(String name) {
      return containsPrometheusMetricName(prometheusName(name));
    }
```

and for performance we could call `containsPrometheusMetricName()` directly.

**Comment by dliu-aspira** [comment]
Yes, this solution can be worked.
![image](https://github.com/user-attachments/assets/a3429702-59a4-4713-9d66-f11f59023766)
