### ISSUE TITLE
Make the library more robust against duplicate metrics

### ISSUE THREAD

**Issue by ewolff** [prometheus/client_java#273]
As #130  and #271 show it is not uncommon to have multiple metrics with the same name registered. Of course this is an error. However, it means that Prometheus will not show any metrics. So it might be preferable to deduplicate the metrics. For example:

* If the same value is reported under the same name more than once the duplicates could just be removed. Log a warning.

* If the have different values the metric could be omitted to make sure no wrong values are reported. Log an error.

**Comment by checketts** [comment]
> If the same value is reported under the same name more than once the duplicates could just be removed. Log a warning.

I could see this taking place in the `TextFormat` class. @brian-brazil would you be open to this?

**Comment by brian-brazil** [comment]
Fundamentally this is a bug elsewhere. Attempting to paper over it in this library will in my opinion only cause further confusion rather than the core problem being fixed.

> If the have different values the metric could be omitted to make sure no wrong values are reported

Metrics that are sometimes there are difficult to deal with semantically.

There is no sane way we can fix badly formed metrics.

**Comment by checketts** [comment]
> There is no sane way we can fix badly formed metrics.

@ewolff Isn't asking for it to repair badly formed metrics, but rather to ensure that badly formed metrics don't affect other legitimate metrics.

Right now the `TextFormat` class streams out the metrics, if it did two passes then it could at least filter out the offenders and log/report them while allowing the well-behaved metrics to still be written out. That is an improvement over current behavior since the service logs make it appear healthy, and the service would need to refer to the Prometheus logs to discover a problem.

**Comment by brian-brazil** [comment]
> @ewolff Isn't asking for it to repair badly formed metrics, but rather to ensure that badly formed metrics don't affect other legitimate metrics.

Making any change to the output makes badly formed metrics affect other metrics. Randomly dropping bad data will only cause more convoluted and harder to debug problems.

Direct instrumentation has protections against duplicate metrics, but for custom collectors it's presumed you know what you're doing. 

I note that all complaints thus far relate to Servo, I'd suggest taking this up with them as they're violating the Spring metrics API. This is not just a Prometheus issue.

**Comment by ewolff** [comment]
While I see your point I think this decision is unfortunate. If people must use flawed metric reporters with Prometheus they will write their own hack to fix the situation or look for other solutions.

**Comment by brian-brazil** [comment]
To be clear the only change we'd ever potentially make around duplicate metrics would be to fail the entire scrape if they were detected. The Go client does this for example, as it has extensive sanity checks.

This may be something we need to consider adding with Prometheus 2.0, as the newer more performant parser doesn't have as many sanity checks - you get logs about the issue instead.

**Comment by checketts** [comment]
That change would be better than nothing since it keeps the error nearer the metrics
