### ISSUE TITLE
Spring boot example for Jetty metrics in Prometheus

### ISSUE THREAD

**Issue by chandresh-pancholi** [prometheus/client_java#324]
Hi,

I have spring boot application and want to send Jetty server metrics to Prometheus. Please suggest how to do it?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
