### ISSUE TITLE
Where to check successfully scraped metrics in prometheus database/server?

### ISSUE THREAD

**Issue by digambarGitHub** [prometheus/client_java#329]
I have applied metric_relable_configs and want to check/test , intended metrics are scraped successfully.
So where I can check on prometheus server/database?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by digambarGitHub** [comment]
Sure.
