### ISSUE TITLE
restful about API Counter

### ISSUE THREAD

**Issue by lishulong16** [prometheus/client_java#349]
API counter + lable?

1. /openapi/user -> method post 
2. /openapi/user -> method get
3. /openapi/user -> method put

**how to metrix api count info ?** 
I think it's better.
```
counter_status_200_openapi_user{method="post"} 10
counter_status__200_openapi_user{method="get"}   20
```
Actually, it is.
```
counter_status__200_openapi_user 30
```
@tokuhirom

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
