### ISSUE TITLE
setting Namespace

### ISSUE THREAD

**Issue by sysmat** [prometheus/client_java#350]
Is there any method in exports to define namespace or prefix for metrics name, I'm using 0.2.0

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by sysmat** [comment]
If I'm using client_java which export metrics why not ask here.

In README there is reference to https://prometheus.io/docs/practices/naming/

Regards, Tomaž
