### ISSUE TITLE
No deletes metrics from the Pushgateway

### ISSUE THREAD

**Issue by sberequek** [prometheus/client_java#361]
Hi, 

with version 0.3.0. of the simpleclient_pushgateway, I tried to remove the metrics with 

`pushGateway.delete("my_job", groupingKeyMap);`
 
and then with

`pushGateway.delete("my_job");`

but are not removed from the pushgateway. It's a bug ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
