### ISSUE TITLE
Removing unwanted gauges 

### ISSUE THREAD

**Issue by Nandy96** [prometheus/client_java#371]
We are using prometheus to monitor cassandra by exposing some table-level and keyspace-level metrics. We find that even after a table has been deleted from the database, the gauges pertaining to those are retained and displayed.

How to eliminate these deprecated gauges?

**Comment by brian-brazil** [comment]
It sounds like you should be using custom collectors rather than direct instrumentation.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
