### ISSUE TITLE
CORS problem when using with Grafana

### ISSUE THREAD

**Issue by anhldbk** [prometheus/client_java#373]
Hi guys,

I'm using this client library to expose a metrics service. The code is simple:

```java
int port = 9233;
HTTPServer server = new HTTPServer(port);
```

But when I try to create a new data source from the service, an unexpected exception is thrown:

![screenshot from 2018-04-12 10-28-11](https://user-images.githubusercontent.com/3270746/38655132-19961c2e-3e3d-11e8-8e72-4ebdf49c64ca.png)

So there's something wrong with CORS headers, isn't it?

**Comment by brian-brazil** [comment]
This is nothing to do with client_java.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
