### ISSUE TITLE
Improve MetricsFilter to report on HTTP status code

### ISSUE THREAD

**Issue by umatrangolo** [prometheus/client_java#381]
Hi,

I'm using the MetricsFilter to plot RPS and P99/P95 of my services but I have just found out that there is no trace of successful/failed requests. 

This metric would be useful to fire alerts whenever the count of 500s/404s or any code != 200 gets over a given threshold.

Given that sounds so obvious and it is surprising that is not there already I was wondering if this has been not implemented by design.

If not I could give it a shot.

**Comment by danieldabate** [comment]
Totally agree with @umatrangolo. We have the same use case and think that this is really useful for everyone.

+1

**Comment by rbarazzutti** [comment]
I also agree with @umatrangolo  and @danieldabate.

The documentation of Prometheus shows even some [nice examples](https://prometheus.io/docs/prometheus/latest/querying/examples/) on what do with that value.

+1

**Comment by rbarazzutti** [comment]
Finally, I wrote some code and did [a pull request](https://github.com/prometheus/client_java/pull/408) for this feature.

**Comment by kdombeck** [comment]
It seems like the [PR](https://github.com/prometheus/client_java/pull/408) is at an impasse.

Currently today the metrics that are created are like the following
```
# HELP http_request The time taken fulfilling servlet requests
# TYPE http_request histogram
http_request_bucket{path="/my/api/1",method="GET",le="0.1",} 3.0
http_request_bucket{path="/my/api/1",method="GET",le="0.25",} 3.0
http_request_bucket{path="/my/api/1",method="GET",le="0.5",} 3.0
http_request_bucket{path="/my/api/1",method="GET",le="0.75",} 3.0
http_request_bucket{path="/my/api/1",method="GET",le="1.0",} 3.0
http_request_bucket{path="/my/api/1",method="GET",le="+Inf",} 4.0
http_request_count{path="/my/api/1",method="GET",} 4.0
http_request_sum{path="/my/api/1",method="GET",} 1.5861285180000002
http_request_bucket{path="/my/api/2",method="GET",le="0.1",} 2.0
http_request_bucket{path="/my/api/2",method="GET",le="0.25",} 2.0
http_request_bucket{path="/my/api/2",method="GET",le="0.5",} 2.0
http_request_bucket{path="/my/api/2",method="GET",le="0.75",} 2.0
http_request_bucket{path="/my/api/2",method="GET",le="1.0",} 2.0
http_request_bucket{path="/my/api/2",method="GET",le="+Inf",} 2.0
http_request_count{path="/my/api/2",method="GET",} 2.0
http_request_sum{path="/my/api/2",method="GET",} 0.007537956
```
And the [PR](https://github.com/prometheus/client_java/pull/408) was suggesting adding **status** to the labels above which @brian-brazil was not comfortable with and I understand his points.

What if rather than adding **status** to the Histogram above like the PR did it added another set of Counters that outputted metrics like the following (Brian mentioned this).
```
# HELP http_request_status HTTP status codes of The time taken fulfilling servlet requests
# TYPE http_request_status counter
http_request_status{path="/my/api/1",method="GET",status="200",} 4.0
http_request_status{path="/my/api/2",method="GET",status="500",} 2.0
```

I think this would satisfy the concerns of not making breaking changes. To take it one step further the new status counter metrics could be disabled by default and clients would need to enable them. That way there would not be any changes to existing clients.

Let me know if this would be acceptable and I will create a PR to make it happen.

**Comment by brian-brazil** [comment]
That would be okay, though there's no need to make it optional. Adding metrics is not a breaking change.

**Comment by kdombeck** [comment]
I created PR https://github.com/prometheus/client_java/pull/560 for this.

**Comment by vizmi** [comment]
When can we expect this to hit the official maven repository? 0.9.0 is the latest I can see and it is from May 2020: https://mvnrepository.com/artifact/io.prometheus/simpleclient

**Comment by brian-brazil** [comment]
This was added, closing.

**Comment by vizmi** [comment]
@brian-brazil can you please confirm when can we see the new code in a publicly available build? maven central has the May 2020 build available as latest.

**Comment by brian-brazil** [comment]
That page takes a while to update, it was put out an hour ago.
