### ISSUE TITLE
Writing exporter with Java

### ISSUE THREAD

**Issue by smallsmallboy** [prometheus/client_java#402]
I don't know how to write exporter on Java in eclipse. Can someone give a basic example?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
