### ISSUE TITLE
question - How do I export the metrics when I already have a HTTP server and not use the provided Http server

### ISSUE THREAD

**Issue by avnerbarr** [prometheus/client_java#421]
I already have a server which can expose an HTTP endpoint `/metrics` 

How do I call the registry and return the dump of metrics to the calling prom server?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by avnerbarr** [comment]
Why are you forcing me to open a google account when there is a github open source issues section?

**Comment by avnerbarr** [comment]
Especially when it is very specific to the java source code
