### ISSUE TITLE
Using CollectorRegistry.getSampleValue in unit tests(java client)

### ISSUE THREAD

**Issue by vestverg** [prometheus/client_java#428]
I really have two questions

1. Last observed value

I have a custom implementation of Collector with GaugeMetricFamily
 and register new observed value  with code similar to this
```java
final GaugeMetricFamily gmf = new GaugeMetricFamily(
                    "some_metric_name",
                    "Some metric help",
                    labelList);
...
gmf .addMetric( labelValues, value)
```

and retrieve the value of metric for asserting with 

```java 
CollectorRegistry.defaultRegistry.getSampleValue("some_metric_name", labelList, labelValues)
```
addMetric add new Sample(..) to list of samples
getSampleValue iterate over the list of samples and return first matching the query options, so if we execute addMetric with same label but different values we will see only first and rest of them, will be ignored. So it's not expected behavior. How I can get actual(last) value?

2. Thread safety of GaugeMetricFamily

GaugeMetricFamily uses underhood simple ArrayList to store observations. ArrayList is not threadsafe. Neither addMetric nor MetricFamilySamplesEnumeration doesn't use any synchronization patterns or concurrent data structures to achieve concurrent access guarantees. 
Or I miss something? Please correct me if I wrong.

**Comment by brian-brazil** [comment]
It sounds like you should be using Gauge rather than GaugeMetricFamily.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
