### ISSUE TITLE
I am new to Prometheus

### ISSUE THREAD

**Issue by debjitk** [prometheus/client_java#490]
I am done coding with the prometheus client library and using simple client_guava. Can some explain me how the metrics are going to reach the prometheus server ?

Also how can I send metrics to telegraf ?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by debjitk** [comment]
My apologies.
