### ISSUE TITLE
prometheus "INVALID" is not a valid start token

### ISSUE THREAD

**Issue by yeyuguang1** [prometheus/client_java#500]
I have the following in my pom:

<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_hotspot</artifactId>
  <version>0.6.0</version>
</dependency>

<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_httpserver</artifactId>
  <version>0.6.0</version>
</dependency>

<dependency>
  <groupId>io.prometheus</groupId>
  <artifactId>simpleclient_pushgateway</artifactId>
  <version>0.6.0</version>
</dependency>
        <dependency>
            <groupId>io.prometheus</groupId>
            <artifactId>simpleclient_spring_boot</artifactId>
            <version>0.6.0</version>
        </dependency>  

when i success start my springboot demo 
     
![图片](https://user-images.githubusercontent.com/26405030/64682385-f66bb880-d4b3-11e9-9700-d44c8e190174.png)

is not valid Prometheus text output. 

so my prometheus can't monitoring,the targets status is down,
![图片](https://user-images.githubusercontent.com/26405030/64682844-c2dd5e00-d4b4-11e9-9c3f-6c5bc7714610.png)

Thanks in advance, Andrew

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
