### ISSUE TITLE
Failure IOException Response code was 307

### ISSUE THREAD

**Issue by maxski** [prometheus/client_java#502]
I would like to send metric with value to prometheus via push gateway.
But I've got the following error: 
_Failure(java.io.IOException: Response code from http://prometheus-pushgateway.social-tech.io/metrics/job/product_metrics was 307)_

Gradle:
`compile group: 'io.prometheus', name: 'simpleclient_pushgateway', version: '0.6.0'`

Java code:
 ```
PushGateway gw = new PushGateway("url");
        gw.setConnectionFactory(new BasicAuthHttpConnectionFactory("user", "pass"));

        Gauge gauge = Gauge.build()
                .name("metricName")
                .help("Description")
                .register();
        gauge.set(metricValue);

        gw.pushAdd(gauge, "jobName");
```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
