### ISSUE TITLE
Is there a way to set common tags/labels?

### ISSUE THREAD

**Issue by lazee** [prometheus/client_java#515]
Hi,

I'm looking for a way to add a common set of labels to all metrics, just like the way MicroMeter handles this: https://micrometer.io/docs/concepts#_common_tags

Is that possible somehow?

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by lazee** [comment]
Thank you. I wasn't aware of that group. Question posted.
