### ISSUE TITLE
Gauge Type can not modify labelNames

### ISSUE THREAD

**Issue by caokegege** [prometheus/client_java#520]
protected final List<String> labelNames;  in  SimpleCollector
no methed can update labelNames

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
