### ISSUE TITLE
best place to set hostname - best practice guide/examples

### ISSUE THREAD

**Issue by genbutsu** [prometheus/client_java#531]
Hi, 
having multiple servers pushing stats to Pushgateway with client_java, the "job" is the best place to save the hostname? 

Is there any best practice guide/examples? (on multiple servers sending the same metrics)
thx

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
