### ISSUE TITLE
simpleclient_spring_boot module not for spring boot 2.x

### ISSUE THREAD

**Issue by PragueJoker** [prometheus/client_java#543]
simpleclient_spring_boot module not for spring boot 2.x,because spring boot 2.x not have AbstractEndpoint this a class

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
