### ISSUE TITLE
metric jvm_memory_pool_allocated_bytes_total usage in Grafana

### ISSUE THREAD

**Issue by Denusdv** [prometheus/client_java#544]
Hello.

I need some help in getting how jvm_memory_pool_allocated_bytes_total should be used.

I have EKS cluster which runs a few based JVM deployments.
Per my understanding jvm_memory_pool_allocated_bytes_total metric provides the current total allocated mem usage by pool type. 
To get the total JVM mem footprint I need to sum all of them.
Now to get it in Grafana

My Grafana query looks like 

`sum(jvm_memory_pool_allocated_bytes_total{instance=~"$instance", service=~"$service", pool=~".*"}) by (instance)`

The result I got doesn't make sense.
What  I'm getting is 

allocated 172.31.66.235:8084 **5.071 TiB**

Notice my JVM is started within docker using the following JVM args

`ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", " XX:+UseCGroupMemoryLimitForHeap", "-jar", "my-jar-1.0.jar"]`

Pls help me to figure out what I'm missing in my usage of the metric

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
