### ISSUE TITLE
Mandatory TYPE and HELP lines

### ISSUE THREAD

**Issue by redfoos** [prometheus/client_java#545]
Hello!

Please tell me why are the HELP and TYPE lines mandatory? Judging by the specification of the prometheus format, they are not mandatory, but the write004 method always writes them.

These lines significantly increase the amount of text sen

**Comment by brian-brazil** [comment]
They're required for client libraries such as this, and ultimately make the output more useful.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
