### ISSUE TITLE
dose simpleclient_pushgateway support https protocol？

### ISSUE THREAD

**Issue by LIANGQI0811** [prometheus/client_java#570]
I noticed that the simpleclient_pushgateway only had example of HTTP，How can I support the HTTPS protocol？

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
