### ISSUE TITLE
Java 1.8 as minimum required version ?

### ISSUE THREAD

**Issue by agavrilov76** [prometheus/client_java#651]
Hi,

I have noticed that a minimal supported Java version is 1.6 which is quite old. Any plans to switch to 1.8?

One of the issues with 1.6 is that it doesn't have a decent Base64 support, so the `pushgateway` module has to use the `javax.xml.bind.DatatypeConverter.printBase64Binary` method from JAXB that is not longer present in the modern Java runtimes (since 10 I think). So the Maven library `javax.xml.bind:jaxb-api` containing `javax.xml.bind` comes as a transitive Maven dependency for `pushgateway`. Now the `javax.xml.bind` has recently been made deprecated in a favour of `jakarta.xml.bind`. Which leads to the situation of having two JAXB implementations being present in the application classpath.

Replacing `javax.xml.bind.DatatypeConverter.printBase64Binary` with `java.util.Base64` in Java 8 would solve this issue :).

Thanks!

As a workaround for my project I'm going to simply exclude  `javax.xml.bind:jaxb-api` in the `pom.xml` which should not cause troubles as long as the job name doesn't have `/` character and the basic auth is not used 😬

**Comment by fstab** [comment]
There are still some people stuck with legacy Java 6 applications that they need to maintain. The current status is that Java 6 is supported until December 2023, sponsored by Zulu (https://en.wikipedia.org/wiki/Java_version_history). Zulu sponsors this for a reason, there is still demand.

That being said, we should fix the `javax.xml.bind ` issue so that you can use `pushgateway` with the latest Java version without workarounds. Base64 encoding is about 20 lines of code (https://en.wikibooks.org/wiki/Algorithm_Implementation/Miscellaneous/Base64), so if this is causing issues, we might consider to copy a Base64 implementation into our code base and get rid of the dependency.

**Comment by dhoard** [comment]
An embedded Base64 encoder would be great to get rid of the `java.xml.bind` dependency.

The algorithm in WikiBooks ((https://en.wikibooks.org/wiki/Algorithm_Implementation/Miscellaneous/Base64) is grossly inefficient, but **migbase64** has a fast (similar performance to the post Java 6 implementation) implementation that has a BSD license.

Would the BSD license be compatible with the Apache 2.0 license used by Prometheus?

If so, putting it in `client_java/simpleclient_common` would be very easy.

**Comment by dhoard** [comment]
PR https://github.com/prometheus/client_java/pull/698 to remove `java.xml.bind` dependency

@fstab please review

**Comment by dhoard** [comment]
@agavrilov76 code has been merged that should resolve the issue. Please test/review.

**Comment by agavrilov76** [comment]
@dhoard looks good! thanks.

**Comment by dhoard** [comment]
> @dhoard looks good! thanks.

Thanks for the update. Please close the issue.
