### ISSUE TITLE
Histogram : have different buckets for different metric of the same metric family

### ISSUE THREAD

**Issue by camathieu** [prometheus/client_java#657]
With the current implementation it is not possible to specify different bucket for different labels set of the same metric

```
request_latency_second{target="rapid"} with buckets of buckets of [5ms,10ms,25ms,50ms,100ms,200ms,500ms,...]
request_latency_second{target="slow"} with buckets of of [1s, 2s, 10s, 30s, 60s, ...]
```

I checked the OpenMetric spec https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md
It mention that the metrics of the same metric family must share the same unit but there is no mention they should share the same buckets.

**Comment by brian-brazil** [comment]
> It mention that the metrics of the same metric family must share the same unit but there is no mention they should share the same buckets.

It does, "Similarly all expositions from any consistent binary and environment of an application SHOULD have the same buckets for a given Histogram MetricFamily, so that they can be aggregated by all ingestors without ingestors having to implement histogram merging logic for heterogeneous buckets."

**Comment by camathieu** [comment]
I missed sorry, thank for pointing out. We'll put the target name in the metric family name I guess.

**Comment by bjung82** [comment]
There are valid use-cases where having different buckets for different label sets are usefull and absolutely necessary!

We have for example  metrics for the duration of outgoing call to external systems. For some calls, durations
in the seconds range are perfectly fine (up to 30s!), and for others (different label set), these have smaller buckets:

Like in the original posting:

request_latency_second{target="rapid"} with buckets of buckets of [5ms,10ms,25ms,50ms,100ms,200ms,500ms,...]
request_latency_second{target="slow"} with buckets of of [1s, 2s, 10s, 30s, 60s, ...]

It is not necessary (and not done) to aggretate these two metrics, but they have to be modelled in this way, to provide
e.g. generic dashboards in Grafana (repeating rows). The metrics model the same concept, therefore they are in the
same familiy with the same name. Of course having the possibility to specify different buckets is a must in this setting,
otherwise the buckets had to be a union of all buckets, which would lead to uniform buckets, but 75 of them (instead
of < 10), and most of these would be useless and a wast of resources in prometheus.
