### ISSUE TITLE
tag format for Graphite client

### ISSUE THREAD

**Issue by liukun4515** [prometheus/client_java#664]
If we want send the tagged carbon format.
In the doc, https://graphite.readthedocs.io/en/latest/tags.html

We should use the ';' to split the metric name, tags values.

But the graphite client is error.

**Comment by fstab** [comment]
Looks like the Graphite Tag Support was added with Graphite release 1.1.X (end of 2017) while the `simpleclient_graphite_bridge` was implemented beginning of 2016. So no wonder that this is missing.

I will put this on my todo list, but it will take some time because I need to find the time to set up Graphite and try it out. If you want to provide a pull request please create one.

**Comment by liukun4515** [comment]
@fstab can i take this issue and file a pull request.
