### ISSUE TITLE
Does prometheus java client support JDK 17? 

### ISSUE THREAD

**Issue by pjgg** [prometheus/client_java#691]
### Questions

Java 17 (LTS) will be released [soon](https://openjdk.java.net/projects/jdk/17/), do you know if prometheus "java simple client" is supported under this JDK version.

**Comment by fstab** [comment]
Our goal is that the Prometheus Java client library works on all Java versions from 6 to 17. If it turns out that there are any issues with Java 17, I will fix them with high priority.

That being said, you cannot compile Java 6 compatible libraries with the Java 17 JDK, because version 17 dropped Java 6 support. So in order to build `client_java` from source, you need Java 11. This has nothing to do with _using_ `client_java` as a Maven dependency in your project. _Using_ `client_java` should work with any Java version.

Please create an issue here if you encounter any issues with Java 17.

**Comment by fstab** [comment]
FYI I added Java 17 to the Java versions compatibility test. The test is green, so far it looks like we are compatible.

https://github.com/prometheus/client_java/blob/master/integration_tests/java_versions/src/test/java/io/prometheus/client/smoketest/JavaVersionsIT.java#L42
