### ISSUE TITLE
Accept header mismatch for OpenMetrics

### ISSUE THREAD

**Issue by jonatan-ivanov** [prometheus/client_java#702]
The `latest`(2.30.0) version of Prometheus sends out the following request when scraping:
```
GET /actuator/prometheus HTTP/1.1
Host: host.docker.internal:8080
User-Agent: Prometheus/2.30.0
Accept: application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1
Accept-Encoding: gzip
X-Prometheus-Scrape-Timeout-Seconds: 10
```

In the `Accept` header, the version of `openmetrics-text` is `0.0.1` (see [`scrape.go`](https://github.com/prometheus/prometheus/blob/1681a8d5393a8d5e3eb8f785b85f477c627e2fd1/scrape/scrape.go#L722)).
In the Java client,  the `Content-Type` constant does not match to this, its version is `1.0.0` (see [`TextFormat`](https://github.com/prometheus/client_java/blob/7a29af04821cd51592c45ce4682c3132372f4c5d/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L25)):
```
CONTENT_TYPE_OPENMETRICS_100 = "application/openmetrics-text; version=1.0.0; charset=utf-8";
```

The python client uses `0.0.1` too. Shouldn't all use the same version (`1.0.0`) or should the Java client use (`0.0.1`)?

It also seems that `TextFormat::chooseContentType` takes this into account:
https://github.com/prometheus/client_java/blob/7a29af04821cd51592c45ce4682c3132372f4c5d/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java#L37-L41

**Comment by dhoard** [comment]
@jonatan-ivanov In my **_opinion_** The calling clients should be fixed to send `application/openmetrics-text; version=1.0.0`

Some analysis (my thought process forming my opinion) from looking at `TextWriter`.

--

`TextWriter` currently only supports two formats...

- text/plain;version=0.0.4

or...

- application/openmetrics-text; version=1.0.0

Because there are currently only two versions of the metrics format supported, any version in the accept header is ignored.

--

Per RFC2616 https://datatracker.ietf.org/doc/html/rfc2616/#section-10.4.7 the server has two options...

- look at the content-type version, and send back a **406 Not Acceptable** if it can't return a response to satisfy the request.

or...

- send back a version that may not be acceptable to the client. The client is responsible for determining if it can handle the content-type returned by the server. (per the Note in RFC2616  https://datatracker.ietf.org/doc/html/rfc2616/#section-10.4.7)

The code has taken the second option, based on the content-type prefix mapping...

- `application/openmetrics-text` -> `application/openmetrics-text; version=1.0.0; charset=utf-8`
- `text/plain` -> `text/plain; version=0.0.4; charset=utf-8`

--

Once additional versions are supported, then I feel that `TextWriter` should be changed to parse/process the version correctly.

**Comment by jonatan-ivanov** [comment]
@dhoard By calling client you mean the Prometheus server right?
So [`scrape.go`](https://github.com/prometheus/prometheus/blob/1681a8d5393a8d5e3eb8f785b85f477c627e2fd1/scrape/scrape.go#L722) should send `application/openmetrics-text; version=1.0.0`, right?

**Comment by dhoard** [comment]
> @dhoard By calling client you mean the Prometheus server right? So [`scrape.go`](https://github.com/prometheus/prometheus/blob/1681a8d5393a8d5e3eb8f785b85f477c627e2fd1/scrape/scrape.go#L722) should send `application/openmetrics-text; version=1.0.0`, right?

That's my **_opinion_**.

As it stands, the version doesn't really matter... at least based on the code in `TextWriter`.

I'm not a maintainer, so there is a likely chance I missed something.

**Comment by jonatan-ivanov** [comment]
Yepp, got it, I agree with you.

**Comment by fstab** [comment]
I agree, too. According to the [OpenMetrics Spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#overall-structure):
> The content type MUST be: application/openmetrics-text; version=1.0.0; charset=utf-8

**Comment by hdost** [comment]
This issue should be closed as there's nothing wrong which how the client handles this. It's properly accounting for how potential scrapes might occur. The descrepancy can really only be fixed on the server (prometheus/prometheus) side.

**Comment by jonatan-ivanov** [comment]
Fixed in https://github.com/prometheus/prometheus/pull/9431
