### ISSUE TITLE
Too many different labelvalues ​​cause OOM

### ISSUE THREAD

**Issue by 18230338980** [prometheus/client_java#770]
I have too many different labelvalues, which lead to OOM. How can I get the number of labelvalues in memory that exceeds a custom threshold, and judge whether the labelvalue already exists after the threshold is exceeded. If it does not exist, it will not continue to collect to prevent memory overflow

**Comment by fstab** [comment]
There is no direct API to do that. You could iterate over all samples like this
```java
    for (java.util.Enumeration<Collector.MetricFamilySamples> mfs = CollectorRegistry.defaultRegistry.filteredMetricFamilySamples(name -> name.equals("my_metric_name")); mfs.hasMoreElements();) {
      for (Collector.MetricFamilySamples.Sample sample : mfs.nextElement().samples) {
        for (int i=0; i<sample.labelNames.size(); i++) {
          String labelName = sample.labelNames.get(i);
          String labelValue = sample.labelValues.get(i);
          // compare labelName and labelValue
        }
      }
    }
```

However, it sounds like a bad idea for two reasons:
* You will have missing metrics after you reached the limit. It's hard to do anything useful with metrics in the monitoring backend if you cannot be sure the metrics will be available.
* If you have so many labels that your JVM runs out of memory, then you will certainly get memory issues in Prometheus as well.

I think it would be better to reconsider what to use as a label so that you end up with significantly less label values.

**Comment by SWYZZWH** [comment]
So is there a benchmark report about how many children can be held without OOM or any solutions to recycle children I don't need any longer? In my case, tens of thousands of jobs which need to be monitored are running on a same physical machine and new jobs are created all the time.

**Comment by fstab** [comment]
> any solutions to recycle children I don't need any longer?

There is a method `SimpleCollector.remove(String... labelValues)` that you can call on `Counter`, `Gauge`, `Histogram`, and `Summary`. So if you don't need specific label values anymore, you can remove that child to free up memory.
