### ISSUE TITLE
What is best practice to query datas use java?

### ISSUE THREAD

**Issue by Joey777210** [prometheus/client_java#816]
Looking for best practice, I'm using raw HTTP APIs now, but is't not convenience for write codes and debug.
Thans for anyones answer!

**Comment by fstab** [comment]
I'm not quite sure what you mean. Usually you store metric data in a time series database like Prometheus and query that data using the PromQL query language. What do you want to achieve?

**Comment by Joey777210** [comment]
If I want to query data in a  Java project, is the best way writing PromQL in a String and pass to Prometheus throw HTTP? Is there a query Lib?  
In this way, do I make the question clear?

**Comment by fstab** [comment]
Prometheus is a time series database. That means it does not only have the current value of metrics, but also the history of previous values.

A good example why this is needed is a request count for an HTTP service, something like `http_requests_total`. If you just know the current value, it tells you nothing. However, if you know how much the count has increased over the past 5 minutes, this is valuable information, because it gives you the the request rate based on a 5 minute time window.

For many cases, you need the time series data. You can only get that when querying Prometheus, not from a client library.
