### ISSUE TITLE
Simpleclient should support quantile

### ISSUE THREAD

**Issue by wangjingbomail** [prometheus/client_java#85]
Hi,  I find that in java client , Summary support quantile, It can use targetQuantile method.
but in simple client ,Summary do not have a targetQuantile method。

Two questions:
1.Will you support targetQuantil later or will not support in simple client?
2.Is there any substitute way to use quantile now in simpleclient

Thank you

**Comment by brian-brazil** [comment]
It's generally recommended to use histograms rather than quantiles, as they're much cheaper and also aggregatable.

**Comment by juliusv** [comment]
It'd still be great to answer the question though :) Would PRs to add quantiles to the simpleclient be welcome at all? They are still useful in some scenarios, and histograms are problematic in some areas, like when it's hard to choose the right bucket sizes in advance.

**Comment by beorn7** [comment]
If somebody would invest the effort and add quantiles to client_java, that would be highly appreciated. Several at SoundCloud wanted to do it, but got distracted.

Whoever wants to do it, needs to take into account, that Java has a dependency problem, so we don't want to pull in heavy dependencies because every user of client_java has to deal with those dependencies then. In case of quantile computation, it is tempting to pull in one of the existing libraries to estimate quantiles. This has to be vetted carefully.

**Comment by brian-brazil** [comment]
A PR would be accepted, as long as it doesn't introduce dependencies. Practically speaking that means copying over the required bits of HDRHistogram and adding benchmarks for it.

> that Java has a dependency problem, so we don't want to pull in heavy dependencies because every user of client_java has to deal with those dependencies then. 

This is not just a technical problem, many developers have adverse reactions to dependencies. In order to avoid that reaction preventing usage of the client (and the technical issues), this client has no dependencies.

**Comment by brian-brazil** [comment]
Fixed by #134
